baseURL: https://marcandregoyette.com/
title: Marc-André Goyette
theme: marcandregoyette
# Languages
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
  fr:
    contentDir: content/fr
    languageName: Français
    weight: 2
# Taxonomies
taxonomies:
  tag: tags
# RSS
languageCode: en
author:
  name: Marc-André Goyette
params:
  feedEntriesLimit: 10
# Markup
markup:
  highlight:
    style: solarized-light
mediaTypes:
  application/atom+xml:
    suffixes:
    - xml
outputFormats:
  atom:
    name: atom
    baseName: atom
    isPlainText: false
    mediaType: application/atom+xml
outputs:
  home:
  - HTML
  - atom
  term:
  - HTML
  - atom
disableKinds:
  - RSS
