baseURL: https://marcandregoyette.com/
title: Marc-André Goyette
theme: marcandregoyette
# Languages
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    contentDir: content/en
    languageName: English
    weight: 1
  fr:
    contentDir: content/fr
    languageName: Français
    weight: 2
# Taxonomies
taxonomies:
  tag: tags
# RSS
languageCode: en
author:
    name: Marc-André Goyette
# Markup
markup:
  highlight:
    style: solarized-light
