#!/bin/bash
set -e

echo "Removing files from the previous build in ../magoyette.github.io/"

# dotfiles aren't globbed, so .git isn't deleted
rm -rf ../magoyette.github.io/*

echo "Copying files from the current build to ../magoyette.github.io/"

cp -r ./dist/* ../magoyette.github.io
