#!/bin/bash
set -e

echo "*****"
echo "Exporting site in ./dist"
echo "*****"

lein export

echo "*****"
echo "Formatting HTML"
echo "*****"

npm run format-html

echo "*****"
echo "Removing files from the previous build in ../magoyette.github.io/"
echo "*****"

# dotfiles aren't globbed, so .git isn't deleted
rm -rf ../magoyette.github.io/*

echo "*****"
echo "Copying files from the current build to ../magoyette.github.io/"
echo "*****"

cp -r ./dist/* ../magoyette.github.io
